gotrip {
  database {
    url = "jdbc:postgresql://localhost:5432/gotrip"
    user = "gotrip_user"
    password = "secret"
    driver = "org.postgresql.Driver"
    connection-pool {
      max-size = 10
      minimum-idle = 2
    }
  }
}