create type location_type as enum (
  'COUNTRY',
  'CITY',
  'AIRPORT',
  'TRAIN_STATION',
  'BUS_STATION',
  'PORT',
  'HOTEL',
  'MEETING_POINT',
  'ATTRACTION',
  'OTHER'
);

create table locations (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  type location_type not null,
  country varchar(255),
  city varchar(255),
  address text,
  latitude double precision,
  longitude double precision
);

create index idx_locations_type on locations (type);
create index idx_locations_lower_country on locations (lower(country));
create index idx_locations_lower_city on locations (lower(city));

insert into locations (name, type, country, city, address, latitude, longitude)
values
  (
    'Noi Bai International Airport',
    'AIRPORT',
    'Vietnam',
    'Hanoi',
    'Phu Minh, Soc Son, Hanoi',
    21.2187,
    105.8042
  ),
  (
    'Hoan Kiem Lake',
    'ATTRACTION',
    'Vietnam',
    'Hanoi',
    null,
    null,
    null
  );
