create type location_type as enum (
  'COUNTRY',
  'CITY',
  'AIRPORT',
  'TRAIN_STATION',
  'BUS_STATION',
  'PORT',
  'HOTEL',
  'MEETING_POINT',
  'ATTRACTION',
  'OTHER'
);

create type trip_status as enum (
  'PLANNED',
  'ACTIVE',
  'COMPLETED',
  'CANCELLED'
);

create type provider_type as enum (
  'AIRLINE',
  'HOTEL',
  'TOUR_COMPANY',
  'TRANSPORT_COMPANY',
  'BOOKING_PLATFORM',
  'INSURANCE_COMPANY',
  'OTHER'
);

create type service_type as enum (
  'FLIGHT',
  'TRAIN',
  'BUS',
  'HOTEL',
  'TOUR',
  'CAR_RENTAL',
  'INSURANCE',
  'TAXI',
  'ESIM',
  'LOUNGE',
  'EXTRA_BAGGAGE',
  'OTHER'
);

create table locations (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  type location_type not null,
  country varchar(255),
  city varchar(255),
  address text,
  latitude double precision,
  longitude double precision
);

create index idx_locations_type on locations (type);
create index idx_locations_lower_country on locations (lower(country));
create index idx_locations_lower_city on locations (lower(city));

create table providers (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  type provider_type not null,
  website varchar(2048),
  support_contact varchar(255)
);

create unique index uq_providers_lower_name on providers (lower(name));
create index idx_providers_type on providers (type);

create table additional_services (
  id bigint generated by default as identity primary key,
  title varchar(255) not null,
  description text,
  service_type service_type not null,
  provider_id bigint references providers (id),
  location_id bigint references locations (id),
  price_amount double precision,
  price_currency varchar(10),
  is_active boolean not null default true,
  constraint chk_additional_services_price_nonnegative check (
    price_amount is null
    or price_amount >= 0
  )
);

create index idx_additional_services_service_type on additional_services (service_type);
create index idx_additional_services_provider_id on additional_services (provider_id);
create index idx_additional_services_location_id on additional_services (location_id);
create index idx_additional_services_is_active on additional_services (is_active);
create index idx_additional_services_lower_title on additional_services (lower(title));

create table trips (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  title varchar(255) not null,
  start_date date,
  end_date date,
  status trip_status not null default 'PLANNED',
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint chk_trips_date_range check (
    start_date is null
    or end_date is null
    or start_date <= end_date
  )
);

create index idx_trips_user_id on trips (user_id);
create index idx_trips_status on trips (status);

create table trip_locations (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references trips (id) on delete cascade,
  location_id bigint not null references locations (id),
  visit_order integer not null,
  arrival_date timestamp with time zone,
  departure_date timestamp with time zone,
  constraint chk_trip_locations_visit_order_positive check (visit_order > 0),
  constraint chk_trip_locations_date_range check (
    arrival_date is null
    or departure_date is null
    or arrival_date <= departure_date
  ),
  constraint uq_trip_locations_trip_visit_order unique (trip_id, visit_order)
);

create index idx_trip_locations_trip_id on trip_locations (trip_id);
create index idx_trip_locations_location_id on trip_locations (location_id);

insert into locations (name, type, country, city, address, latitude, longitude)
values
  (
    'Noi Bai International Airport',
    'AIRPORT',
    'Vietnam',
    'Hanoi',
    'Phu Minh, Soc Son, Hanoi',
    21.2187,
    105.8042
  ),
  (
    'Hoan Kiem Lake',
    'ATTRACTION',
    'Vietnam',
    'Hanoi',
    null,
    null,
    null
  );
